### ISSUE TITLE
Vite 6: TypeError: vite:css-analysis plugin transform is not a function

### ISSUE THREAD

**Issue by aeharding** [privatenumber/vite-css-modules#13]
### Problem

Hi there! I am testing my build setup with vite 6 beta, and I noticed vite fails.

when I remove the `patchCssModules` plugin the error goes away.

### Expected behavior

No errors

### Minimal reproduction URL

https://stackblitz.com/edit/vitejs-vite-8sjmgl?file=package.json

### Version

v1.6.0

### Node.js version

v18.20.3

### Package manager

pnpm

### Operating system

Linux

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Thanks for the issue.

I probably won't have a chance to work on this until Vite 6 is stable and I'm encountering this problem myself.

If you want to work on it though, feel free to open a PR.

**Comment by skewballfox** [comment]
looked into this a little bit. It seems that `configureServer` from css-analysis is undefined. Looking through the cssAnalysis def it seems the returned server config was removed in [this PR](https://github.com/vitejs/vite/pull/16471). I can try to see if I can fix it myself in a bit
