### ISSUE TITLE
More readable error when trying to compose class that doesn't exist

### ISSUE THREAD

**Issue by axelboc** [privatenumber/vite-css-modules#2]
### Feature request

Improve error message when trying to compose a class that doesn't exist in the target CSS module.

### Motivations

Thank you so much for looking into these CSS Modules issues! I'm still testing but the first problem I encountered was the following error:

```
Internal server error: Cannot read properties of undefined (reading 'exportAs')
```

It occurred on a `composes` declaration in which the class I was trying to compose did not exist in the target CSS module. This kind of issue was not reported previously, so it's such a nice win that it is now!!

Since the error message is a bit cryptic, would it be possible to rethrow a clearer error message?

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Thanks for reporting this.

Since this bug wasn't reported/tracked in Vite, I filed it here: https://github.com/vitejs/vite/issues/16075
