### ISSUE TITLE
Hot module replacement

### ISSUE THREAD

**Issue by axelboc** [privatenumber/vite-css-modules#3]
### Problem

You're probably aware of it already, but CSS modules are no longer reloaded automatically on change with this plugin. Even refreshing the page doesn't seem to work; I have to restart the server to see changes.

### Expected behavior

Any changes to CSS modules should appear right away in the browser in development, without restarting/reloading.

### Minimal reproduction URL

NA

### Version

5.1.0

### Node.js version

20

### Package manager

pnpm

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Thanks for the issues!

Can you provide a minimal reproduction for this? It works fine for me.

**Comment by axelboc** [comment]
Hmm maybe it's related with my TS monorepo set-up. I have an `app` project that depends on a `lib` project. The `app` imports the `lib`'s source files directly; there's no build step.

- When I save a CSS module located inside `app`, I do see an "hmr update" log in the terminal, but nothing changes in the browser.
- When I save a CSS module located inside `lib`, nothing happens at all; I have to restart the server.

I'll try to make a repro.

**Comment by privatenumber** [comment]
I was able to reproduce the bug: 
https://stackblitz.com/edit/vitejs-vite-zc8bbp?file=src%2Fstyle.module.css

I had fixed it in https://github.com/vitejs/vite/pull/16018, but forgot to port the fix back to this plugin. Thanks for catching! Will be fixed shortly.

I also found that HMR doesn't currently work in CSS Module dependencies in Vite: https://github.com/vitejs/vite/issues/16074

**Comment by privatenumber** [comment]
I added this demo to the README to confirm HMR is working:
https://stackblitz.com/edit/vitejs-vite-v9jcwo?file=src%2Fstyle.module.css

**Comment by axelboc** [comment]
Awesome, glad you were able to reproduce!

I forked your repro because I'm still having issues when coupled with the `@vitejs/plugin-react` plugins. I get page reloads instead of hot replacements: https://stackblitz.com/edit/vitejs-vite-15bgs7
