### ISSUE TITLE
moduleGraph.createFileOnlyEntry is not a function

### ISSUE THREAD

**Issue by arthow4n** [privatenumber/vite-css-modules#4]
### Problem

On version 1.3.0 I get the error message below when importing a CSS module, which the bug didn't exist on 1.2.0:

```
13:50:22 [vite] Internal server error: moduleGraph.createFileOnlyEntry is not a function
  Plugin: vite:css-analysis
  File: C:/<redacted>/<redacted>/global.module.scss
      at TransformContext.transform (file:///C:/<redacted>/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:31762:43)
      at TransformContext.viteCssAnalysisPlugin.transform (C:\<redacted>\node_modules\vite-css-modules\dist\index.cjs:912:20)
      at Object.transform (file:///C:/<redacted>/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:50838:62)
      at async loadAndTransform (file:///C:/<redacted>/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:53611:29)
      at async viteTransformMiddleware (file:///C:/<redacted>/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:63409:32)
```

I believe it's because in the HMR fix introduced in 1.3.0 https://github.com/privatenumber/vite-css-modules/blob/f71b54ef223f3354f0790f1e20f130d3559fd38c/src/patch.ts#L117 there the intercepted server's `moduleGraph` didn't have a correct prototype of class `ModuleGraph`:

```
    const interceptedServer = {
      moduleGraph: { // <-- Here it's an object literal not inheriting from class ModuleGraph, so `moduleGraph.prototype.createFileOnlyEntry` is undefined
        getModuleById: (id) => {
```

I was able to fix(?) the issue locallly by reusing the original object instead and binding the method:

```patch
diff --git a/dist/index.cjs b/dist/index.cjs
index 8ad49f5e28426e4a389de8831b8f67bc403487a8..f6e8e44146c1463190bcc06075bb56d29ec5ac89 100644
--- a/dist/index.cjs
+++ b/dist/index.cjs
@@ -892,18 +892,15 @@ const supportCssModulesHMR = (vitePlugins) => {
   }
   const tag = "?SPOOF?inline";
   viteCssAnalysisPlugin.configureServer = function(server) {
-    const interceptedServer = {
-      moduleGraph: {
-        getModuleById: (id) => {
-          const tagIndex = id.indexOf(tag);
-          if (tagIndex !== -1) {
-            id = id.slice(0, tagIndex) + id.slice(tagIndex + tag.length);
-          }
-          return server.moduleGraph.getModuleById(id);
-        }
+    const orig = server.moduleGraph.getModuleById.bind(server.moduleGraph);
+    server.moduleGraph.getModuleById = (id) => {
+      const tagIndex = id.indexOf(tag);
+      if (tagIndex !== -1) {
+        id = id.slice(0, tagIndex) + id.slice(tagIndex + tag.length);
       }
-    };
-    return Reflect.apply(configureServer, this, [interceptedServer]);
+      return orig(id);
+    }
+    return Reflect.apply(configureServer, this, [server]);
   };
   viteCssAnalysisPlugin.transform = async function(css, id, options) {
     if (cssModuleRE.test(id)) {
```

I'm unsure how to make a minimal reproduction of this though.

Anyway, thanks for the amazing plugin 🙏 I'm trying to migrate a legacy project and this plugin really solved the majority of the issues, hope it gets into the upstream soon!

### Expected behavior

Intercepted `moduleGraph` should have prototype `ModuleGraph`.

### Minimal reproduction URL

N/A, I haven't figure out how exactly to make one but I have a workaround to share above.

### Version

1.3.0

### Node.js version

20.11.1

### Package manager

yarn

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by axelboc** [comment]
Can confirm I'm experiencing this with 1.3.0. In my case it seems to be caused by `@import` of `node_modules` packages, like `normalize.css`.

**Comment by axelboc** [comment]
Repro: https://stackblitz.com/edit/vitejs-vite-a1rzqy

**Comment by privatenumber** [comment]
Thanks! This is definitely an issue and oversight on my part.

Would you mind opening a PR with the patch above? I'm currently occupied but I'd happy to accept a PR.

**Comment by arthow4n** [comment]
Thanks for confirming! Will try to work on it later today if no one else has picked it up.
