### ISSUE TITLE
Build breaks for selectors with the name `default`

### ISSUE THREAD

**Issue by pffigueiredo** [privatenumber/vite-css-modules#9]
### Problem

The build breaks if there is a selector with the name of `default`.

e.g.

```css
.default{
...
}

#default{
...
}
```

### Expected behavior

It should be able to handle it OR at least have that caveat in the docs?

### Minimal reproduction URL

https://stackblitz.com/edit/vitejs-vite-mqxms1?file=src%2Fstyle.module.css

### Version

v0.0.1

### Node.js version

v18.20.30

### Package manager

yarn

### Operating system

macOS

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Nice catch! Thanks for the reproduction and showing interest in working on it.
Feel free to ask me any questions if you need. Looking forward to the PR!

**Comment by privatenumber** [comment]
Looked into this and it doesn't seem like Vite w/o this plugin handles this either.

The difference is that it fails silently, which I think is less ideal.

To handle this, maybe we can add a config to disable default exports so the `default` named export can be used.
